# Generated by Django 6.0.2 on 2026-04-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
