# Generated by Django 6.0.2 on 2026-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_subtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='gray', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issues.tag'),
        ),
    ]
