# Generated by Django 6.0.2 on 2026-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_remove_notification_title_notification_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='task.complete', max_length=255),
            preserve_default=False,
        ),
    ]
